---
functional:
  - Представить двум игрокам соревноваться друг с другом в решении задач и видеть написание кода друг у друга
  - Возможность видеть рейтинг участников
  - Возможность игры с ботом
  - Возможность игры с другом по ссылке
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
implicit:
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
